In [26]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout

In [27]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

In [28]:
class_name = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
class_name

['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [29]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((50000, 32, 32, 3), (50000, 1), (10000, 32, 32, 3), (10000, 1))

In [30]:
x_train.min(), x_train.max(), y_train.min(), y_train.max()

(0, 255, 0, 9)

In [31]:
x_train = x_train/255.0
x_test = x_test/255.0

# ANN

In [36]:
ann_model = Sequential([
    Flatten(input_shape = (32,32,3)),
    Dense(units=3000, activation='relu'),
    Dropout(0.2),
    Dense(10, activation='Softmax')
])

In [37]:
ann_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 3072)              0         
                                                                 
 dense (Dense)               (None, 3000)              9219000   
                                                                 
 dropout (Dropout)           (None, 3000)              0         
                                                                 
 dense_1 (Dense)             (None, 10)                30010     
                                                                 
Total params: 9,249,010
Trainable params: 9,249,010
Non-trainable params: 0
_________________________________________________________________


In [38]:
ann_model.compile(optimizer='adam',
                 loss='sparse_categorical_crossentropy',
                 metrics='accuracy')

In [39]:
training = ann_model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1563/1563 [==============================] - 117s 72ms/step - loss: 1.9808 - accuracy: 0.3048
Epoch 2/10
1563/1563 [==============================] - 110s 71ms/step - loss: 1.7980 - accuracy: 0.3533
Epoch 3/10
1563/1563 [==============================] - 111s 71ms/step - loss: 1.7423 - accuracy: 0.3754
Epoch 4/10
1563/1563 [==============================] - 112s 71ms/step - loss: 1.7115 - accuracy: 0.3882
Epoch 5/10
1563/1563 [==============================] - 110s 71ms/step - loss: 1.6831 - accuracy: 0.3986
Epoch 6/10
1563/1563 [==============================] - 111s 71ms/step - loss: 1.6677 - accuracy: 0.4023
Epoch 7/10
1563/1563 [==============================] - 111s 71ms/step - loss: 1.6566 - accuracy: 0.4048
Epoch 8/10
1563/1563 [==============================] - 112s 72ms/step - loss: 1.6367 - accuracy: 0.4145
Epoch 9/10
1563/1563 [==============================] - 113s 72ms/step - loss: 1.6252 - accuracy: 0.4173
Epoch 10/10
1563/1563 [==============================] 

In [40]:
evaluating = ann_model.evaluate(x_test, y_test)

313/313 [==============================] - 9s 26ms/step - loss: 1.5514 - accuracy: 0.4473


In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [58]:
y_pred = np.argmax(ann_model(x_test), axis=-1)
y_pred, y_test

(array([3, 9, 8, ..., 3, 6, 7], dtype=int64),
 array([[3],
        [8],
        [8],
        ...,
        [5],
        [1],
        [7]], dtype=uint8))

In [59]:
cm = confusion_matrix(y_test.reshape(-1, ), y_pred)
a_s = accuracy_score(y_test.reshape(-1, ), y_pred)
cm, a_s

(array([[376,  38,  62,  44,  26,  31,  32,  70, 233,  88],
        [ 27, 534,   7,  31,   5,  34,  18,  47,  87, 210],
        [ 58,  20, 253, 131,  90,  91, 190, 108,  38,  21],
        [ 12,  18,  68, 316,  22, 224, 160,  86,  35,  59],
        [ 36,  10, 121,  78, 234,  61, 251, 149,  34,  26],
        [  5,  10,  77, 240,  29, 362, 109, 109,  33,  26],
        [  5,  14,  52, 128,  49,  41, 629,  36,  16,  30],
        [ 14,  17,  35,  79,  45,  85,  54, 571,  27,  73],
        [ 66,  77,  11,  34,  12,  24,  21,  19, 640,  96],
        [ 20, 145,  11,  54,   6,  24,  30,  57,  95, 558]], dtype=int64),
 0.4473)

# CNN

In [64]:
from keras.layers import Conv2D, MaxPool2D

In [68]:
cnn_model = Sequential([
    Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(32,32,3)),
    MaxPool2D((2,2)),
    
    Conv2D(filters=64, kernel_size=(3,3), activation='relu'),
    MaxPool2D((2,2)),
    
    Flatten(input_shape=(32,32,3)),
    Dense(units=64, activation='relu'),
    Dense(10, activation='Softmax')
])

In [69]:
cnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics='accuracy')

In [70]:
cnn_model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1563/1563 [==============================] - 66s 40ms/step - loss: 1.4720 - accuracy: 0.4737
Epoch 2/10
1563/1563 [==============================] - 60s 38ms/step - loss: 1.1104 - accuracy: 0.6108
Epoch 3/10
1563/1563 [==============================] - 61s 39ms/step - loss: 0.9715 - accuracy: 0.6618
Epoch 4/10
1563/1563 [==============================] - 61s 39ms/step - loss: 0.8894 - accuracy: 0.6907
Epoch 5/10
1563/1563 [==============================] - 62s 40ms/step - loss: 0.8180 - accuracy: 0.7176
Epoch 6/10
1563/1563 [==============================] - 60s 38ms/step - loss: 0.7656 - accuracy: 0.7334
Epoch 7/10
1563/1563 [==============================] - 61s 39ms/step - loss: 0.7220 - accuracy: 0.7482
Epoch 8/10
1563/1563 [==============================] - 62s 40ms/step - loss: 0.6809 - accuracy: 0.7634
Epoch 9/10
1563/1563 [==============================] - 60s 39ms/step - loss: 0.6355 - accuracy: 0.7795
Epoch 10/10
1563/1563 [==============================] - 61s 39m

In [71]:
cnn_model.evaluate(x_test, y_test)

313/313 [==============================] - 8s 23ms/step - loss: 0.9369 - accuracy: 0.7034


[0.9369294047355652, 0.7034000158309937]

In [79]:
y_pred=np.argmax(cnn_model.predict(x_test), axis=-1)

313/313 [==============================] - 8s 26ms/step


In [81]:
y_pred, y_test

(array([3, 8, 8, ..., 7, 4, 7], dtype=int64),
 array([[3],
        [8],
        [8],
        ...,
        [5],
        [1],
        [7]], dtype=uint8))

In [82]:
y_pred, y_test.reshape(-1, )

(array([3, 8, 8, ..., 7, 4, 7], dtype=int64),
 array([3, 8, 8, ..., 5, 1, 7], dtype=uint8))

In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
a_s = accuracy_score(y_test, y_pred)
cm, a_s

(array([[757,  20,  52,  11,  22,   5,   7,  10,  96,  20],
        [ 27, 828,  11,   5,   8,   2,  15,   6,  42,  56],
        [ 64,   5, 520,  49, 135,  55,  94,  59,  15,   4],
        [ 30,  10,  65, 465, 106, 126, 104,  69,  21,   4],
        [ 25,   2,  47,  32, 677,  19,  82,  99,  16,   1],
        [ 12,   6,  45, 157,  80, 552,  37,  98,  10,   3],
        [  7,   2,  32,  38,  33,  10, 860,  10,   5,   3],
        [ 16,   3,  31,  22,  59,  35,  12, 810,   6,   6],
        [ 57,  28,   9,   9,  11,   6,  10,   7, 852,  11],
        [ 39, 106,  15,  13,  11,  12,  11,  28,  52, 713]], dtype=int64),
 0.7034)